### ISSUE TITLE
Python code?

### ISSUE THREAD

**Issue by perkinglors** [rouyang2017/SISSO#11]
Hi Dr. Ouyang, do you have a copy of SISSO code based on Python?

**Comment by rouyang2017** [comment]
Hi perkinglors, unfortunately my Python skill is poor. It should be doable to convert to Python, or make a Python interface? One concern is that will the Python code still be as efficient as  that by FORTRAN when dealing big-data and involving massive palatalization?

**Comment by nikoltchovskaa** [comment]
@perkinglors You can easily call Fortran code from Python using the [subproccess](https://docs.python.org/3/library/subprocess.html) module. Like this: `subprocess.run(['mpirun','path/to/compiled/version/of/sisso'], encoding='utf-8' )`.
