### ISSUE TITLE
Question about mpiifort 

### ISSUE THREAD

**Issue by nhjkjh0608** [rouyang2017/SISSO#12]
At mpiifort -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o ~/bin/your_code_name 

May I ask for example of ~/bin/your_code_name ??
What file should I put after -o tag??

**Comment by rouyang2017** [comment]
For example: -o ~/bin/SISSO.3.0
which means you compile the program and output a code named SISSO.3.0 put in the folder ~/bin
