### ISSUE TITLE
Double counting in multiclass classification.

### ISSUE THREAD

**Issue by pritwish** [rouyang2017/SISSO#13]
Hi Dr.Ouyang, i am running a multiclass (5) classification problem with about 736 data points. In the output file, I get something like this

Number of data in all overlap regions (the first metric):       300
Size of the overlap (the second metric):        0.32131
Actual number (without double counting) of data in all overlap regions:        204

Can you please elaborate a bit more on what 'double counting' is over here. I have some assumptions but I fear I might have it wrong. 
Also my classes are distributed unevenly (179   68  373   68   48), will this imbalance affect my output?

p.s. I am running the ST-SISSO version.

**Comment by rouyang2017** [comment]
In the SISSO paper, there is a definition for the number of overlap_data, which is used for model selection in the SISSO code. This may involve double counting if you have more than two classes. For example, if there are classes A, B, C, and one data of A is in the overlap region between both A and B and in the overlap region between A and C, then that data will be counted twice. 

The number 204 you showed above is without that double counting. For example, you can count totally how many unclassified materials ('0') in the descriptor files of the desc_data folder, and you should find it 204.

"distributed unevenly (179 68 373 68 48)" will not affect output.
