### ISSUE TITLE
Questions about space_001d.name and space_002d.name

### ISSUE THREAD

**Issue by nhjkjh0608** [rouyang2017/SISSO#14]
Hello I tried classification task using example train.dat posted on your github.

I have 2 questions about space_001d.name and space_002d.name

1. In space_001d.name file, what does N and S exactly mean??
2. In space_002d.name file, why does S value missing??

Thank you

**Comment by rouyang2017** [comment]
1. In the one dimensional space of the feature of interest, data of different groups are distributed in different segments, and the segments may overlap.  The N and S denote the number of data in the overlap of segments and the size of the overlap, respectively.  Features are evaluated individually, and those with small N and S will be highly scored.
2. I don't see that problem. Are you using v3.0?

**Comment by nhjkjh0608** [comment]
Thank you for your kind answer

Yes I am using v3.0

![20190823_105750](https://user-images.githubusercontent.com/25633919/63561450-e50a4d00-c594-11e9-96b9-ee2cb9238413.png)

This image is capture of space_002d.name file generated with using test data on your github
