### ISSUE TITLE
What number should be specified in L1L0_size4L0 if method="L0"?

### ISSUE THREAD

**Issue by hS-Sayuri** [rouyang2017/SISSO#15]
I just choose method='L0' and leave the L1L0_size4L0 blank and then get an error in this term. It seems that I have to fill something here to make the program run normally.

**Comment by rouyang2017** [comment]
The 'L1L0_size4L0' is useless when method=L0 but the code try to read something. 
Please set it an arbitrary integer to suppress the problem. I will let blank legal.
