### ISSUE TITLE
Question about regenerating your metal/non-metal classifier

### ISSUE THREAD

**Issue by nhjkjh0608** [rouyang2017/SISSO#17]
Hello

I am trying to regenerate your non-metal/metal classifier in your paper.
But when I tried to regenerate with this SISSO.in, I couldn't get same results as you.
May I ask which parameter is wrong??

![image](https://user-images.githubusercontent.com/25633919/66620332-0c87a880-ec1b-11e9-80c2-dec6fbb90f8a.png)

Order of primary feature in train.dat

![image](https://user-images.githubusercontent.com/25633919/66620354-1d381e80-ec1b-11e9-8da7-06292bab0a88.png)

**Comment by rouyang2017** [comment]
![图片1](https://user-images.githubusercontent.com/32838731/66716308-d014a200-edfe-11e9-85c9-12821fd07a58.png)
![图片2](https://user-images.githubusercontent.com/32838731/66716310-dc006400-edfe-11e9-87f8-eb3ec37ac097.png)
![图片3](https://user-images.githubusercontent.com/32838731/66716312-de62be00-edfe-11e9-81f0-e545226ee98a.png)

**Comment by rouyang2017** [comment]
Hi, please see my attached pictures.  In particular, the data is (188,108). That three 'problem data' were left out in order to find a no-overlap model.  Note that n the last picture you see #data_overlap 2 for the first three descriptors because of the boundary tolerance, but in fact no overlap.

**Comment by nhjkjh0608** [comment]
Thank you for your kind reply :)
