### ISSUE TITLE
SISSO div0 problem

### ISSUE THREAD

**Issue by MilenaOehlers** [rouyang2017/SISSO#18]
Hello, I am working with the SISSO.3.0 version of June 2019 and encountering the following problem:
It sometimes happens that SISSO fit returns a model that due to division/log by featureA or division/log by (featureB-featureC) is of no use for applying SISSO predict, if in the prediction.dat featureA or (featureB-featureC) contains a 0 (or very small value). As I am embedding SISSOfit and -predict into a loop in which each iteration is dependent of the previous one, this causes some problems as the code stops execution at that point. I can program a workaround for this using the models and feature_space folder, but an automatic reselection of the next best model in case of failure of the chosen one could be worth implementing into the next SISSO version? Thanks in advance!

**Comment by rouyang2017** [comment]
Hi, I understand your problem, and I had such problem too. The possible solutions could be (1) like you said, reselection of the next best model (2) in the folder feature_space, create a file named "reject.name" and then copy the 'bad' features into the file reject.name. The code will detect if the file reject.name exist, and if yes, the provided features will not be generated.
