### ISSUE TITLE
SISSO input target feature

### ISSUE THREAD

**Issue by nikoltchovskaa** [rouyang2017/SISSO#19]
Hello Dr. Ouyang, 

I am doing some experiments with SISSO and I am wandering how SISSO figures out which column is the target feature? If I understood it right, in `train.dat_classification` this is the materials-column and in `train.dat_regression` this is the property-column? If I want to run it on my own dataset how should I name my target variable? Is the name important? 

Thank you in advance!

**Comment by rouyang2017** [comment]
Hi,
The names are not relevant, and you may choose any strings you like (excluding special symbols e.g. +, -, abs).
For classification, the code will read SISSO.in where your data group information are specified, and in the train.dat file you arrange your data accordingly. For example, (3,5) in SISSO.in means that in the train.dat you will have the first 3 data for group1 and the following 5 data for group2.
For regression, target-property values are given in the first column(s) in the file train.dat.

**Comment by nikoltchovskaa** [comment]
Thank you very much for the quick answer!
