### ISSUE TITLE
LS_RSME

### ISSUE THREAD

**Issue by vonruti** [rouyang2017/SISSO#2]
How is the LS_RSME exactely calculated? How is the data split into training and learing set? Could you plead add this in the documentation? It is not clear if this is done the same way as in your paper.

**Comment by rouyang2017** [comment]
Thank you! The LS_RMSE is defined as the root mean squared error (RMSE) of the model fitted by least square (LS) fitting: sqrt(sum[(y_true-y_model)^2]/n).  There is no data splitting scheme in the SISSO code, and SISSO reads only training data. In the SISSO paper, the data splitting is a separate procedure, not inside the SISSO code.
