### ISSUE TITLE
Error: forrtl: severe (64): input conversion error, unit -5, file Internal List-Directed Read

### ISSUE THREAD

**Issue by MilenaOehlers** [rouyang2017/SISSO#20]
Hello, 
I executed SISSO_predict from the terminal (after successful installation and previous successful executions) and this error appears:
_______________________________________________________________________________
 dimension:            1
 feature: ((Z_A+Z_B)/rP_B)
forrtl: severe (64): input conversion error, unit -5, file Internal List-Directed Read
Image              PC                Routine            Line        Source             
SISSO_predict      00000000004089AB  Unknown               Unknown  Unknown
SISSO_predict      00000000004328D1  Unknown               Unknown  Unknown
SISSO_predict      00000000004315F5  Unknown               Unknown  Unknown
SISSO_predict      0000000000405BFF  Unknown               Unknown  Unknown
SISSO_predict      0000000000402AC2  Unknown               Unknown  Unknown
libc-2.27.so       00007FE78219DB97  __libc_start_main     Unknown  Unknown
SISSO_predict      00000000004029AA  Unknown               Unknown  Unknown
_______________________________________________________________________________

I do not understand the error or what causes it. What I noticed also is that in SISSO.out the following unusual lines appear after executing SISSO (see attached file):
_______________________________________________________________________________
Model/descriptor for generating residual:
       coefficients_001:     0.7195685272E-02
       coefficients_001:     -0.1425151870E-02
          Intercept_001:     0.3607139813E+01
       coefficients_001:     0.5149789758E-01
          Intercept_001:     0.3651808281E+01
       coefficients_001:     0.1518181025E-02
          Intercept_001:     0.3558224874E+01
       coefficients_001:     0.3887855296E-01
          Intercept_001:     0.3705094158E+01
       coefficients_001:     0.3067298966E-02
          Intercept_001:     0.3662611429E+01
================================================================================
          Intercept_001:     0.3677778981E+01
_______________________________________________________________________________
I do not know what causes these lines to appear, either. In previous attempts to run the code, a similar output was generated, with only the 2D descriptor part being skipped (the 3D descriptor followed directly after the 1D descriptor). 

Any idea what happened here?

Thanks in advance!

Milena
[files.zip](https://github.com/rouyang2017/SISSO/files/4053606/files.zip)

**Comment by rouyang2017** [comment]
Hi, SISSO_predict will read in coefficients right after the descriptor, and the error occurs in your case because no coefficients to read after the 1D descriptor in the SISSO.out.  I see the SISSO.out output is in a mess. I didn't see this before and don't know what caused this. What if you run SISSO again with just one core?

Model/descriptor for generating residual:
       coefficients_001:     0.7195685272E-02
       coefficients_001:     -0.1425151870E-02
          Intercept_001:     0.3607139813E+01
       coefficients_001:     0.5149789758E-01
          Intercept_001:     0.3651808281E+01
       coefficients_001:     0.1518181025E-02
          Intercept_001:     0.3558224874E+01
       coefficients_001:     0.3887855296E-01
          Intercept_001:     0.3705094158E+01
       coefficients_001:     0.3067298966E-02
          Intercept_001:     0.3662611429E+01
================================================================================
          Intercept_001:     0.3677778981E+01
  1D descriptor (model): 
Total RMSE,MaxAE:   0.106794  0.340241
@@@descriptor: 
                      7:[((Z_A+Z_B)/rP_B)]
Total number of features in the space phi01:            646
Total number of features in the space phi02:         690942
Size of the SIS-selected subspace from phi02:        100
Wall-clock time (second) for this FC:            0.54

**Comment by MilenaOehlers** [comment]
Thanks for the quick response! I noticed an error in my python code that starts SISSO, after fixing that the problem did not appear anymore, so it might be fixed already. If it reappears later despite the adjustments, I will write here and try out running it on one core. Regards
