### ISSUE TITLE
A problem statement for MT-SISSO

### ISSUE THREAD

**Issue by pritwish** [rouyang2017/SISSO#21]
Hi Dr.Ouyang,

I have multiple properties that need to be predicted from a single dataset (eg bandgap, phonon frequency, etc) using atomic features. Clearly, this is a regression problem. Previously, I was mapping individual properties using the dataset and running it multiple times. In the paper on MT-SISSO you have predicted the relative stability crystal structure for construction of a phase diagram. Can I use this model for my problem?

**Comment by rouyang2017** [comment]
Hi, I think this depends on how your multiple properties are related to each other, and if they do share much in common, then you probably can find a common descriptor with low training error.  You can give a try and see how will be your training of simultaneously vs individually.
