### ISSUE TITLE
CV_RMSE

### ISSUE THREAD

**Issue by pritwish** [rouyang2017/SISSO#22]
Hi! I was just wondering if the cross validation part of the code can be utilized. I have observed that the code calculating the CV is present in the code but for some reason has been set aside (and also has been removed from the input parameters post the first version of the code). Is there any specific reason for this, or could I just un-comment those parts of the code and use that feature?

**Comment by rouyang2017** [comment]
Hi, that "CV_RMSE"(fixing the descriptor and validate only coefficients) was not really CV, and thus has been removed from recent versions to avoid misleading. I suggest you create your CV scheme outside the SISSO code.
