### ISSUE TITLE
missing data representation

### ISSUE THREAD

**Issue by bfocassio** [rouyang2017/SISSO#28]
In the MT-SISSO paper you explain the capability of dealing with missing or unknown data.

How is this represented in the train.dat file?

**Comment by rouyang2017** [comment]
We actually don't need to represent "missing data" in the train.dat file. Please see the template files: train.dat_classification_multitask and train.dat_regression_multitask in the folder "input_template".

**Comment by bfocassio** [comment]
Thank you

Another question, regarding the train.dat_classification_multitask. The first task has 2 groups, and the second task has 3 groups, in the SISSO.in file we would input `nsample` as:

`nsample=(2,3,0),(4,4,3)`

or just:

`nsample=(2,3),(4,4,3)`

**Comment by rouyang2017** [comment]
nsample = (2,3), (4,4,3)

**Comment by bfocassio** [comment]
thank you
