### ISSUE TITLE
Errors with open source compilers

### ISSUE THREAD

**Issue by jcklasseter** [rouyang2017/SISSO#29]
Hi, this may be some user error but I cannot get SISSO compiled using gfortran or mpif90, only ifort. 

For reproducibility I've been using Docker (The same behavior is seen on a clean Ubuntu install, I tried and had a friend try too), since it's 0-overhead usually. I've included some instructions for how to use it, sorry if you know.

Here is the Dockerfile, once you get Docker installed (fairly easy following online docs) you can use this command wherever you download the Dockerfile to: "docker build -t "sisso" ." 

```
FROM ubuntu:latest

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y build-essential

RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y git p7zip-full wget libboost-all-dev make g++9 cmake
RUN DEBIAN_FRONTEND='noninteractive' apt-get install -y libmpich-dev

WORKDIR /root

RUN git clone https://github.com/rouyang2017/SISSO.git

WORKDIR /root/SISSO

#RUN cat src/var_global.f90
RUN sed -i "s/use mpi/include \'mpif.h\'/g" src/var_global.f90 
#RUN sed -i "s/implicit none//" src/var_global.f90
#RUN cat src/var_global.f90

RUN cd src && mpif90 -fimplicit-none var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o ~/SISSO.x

#entry.sh is blank, I'm just working on compilation first
ENTRYPOINT ["/bin/bash", "entry.sh"]

```

I run into this error while building:

```
var_global.f90:18:13:

   18 | implicit none
      |             1
Error: IMPLICIT NONE statement at (1) cannot follow INTERFACE statement at (2)
libsisso.f90:37:4:

   37 | use var_global
      |    1
Fatal Error: Cannot open module file 'var_global.mod' for reading at (1): No such file or directory

```

If I remove the `-fimplicit-none` the same error results. Using `libopenmpi-dev` instead of `libmpich-dev` didn't help, and using `gfortran-8` did not help.

If you want to debug, you can comment out the make line in the Dockerfile and build it like above.

However if you , then to run that SISSO tag, "docker run --entrypoint /bin/bash -I sisso"

Are we forced in to using intel compilers, or is there any way I'm missing something with the other compilers?

Thanks for your time

**Comment by rouyang2017** [comment]
Hi, I am not familiar with Docker, but mpif90 and mpigfortran should work too. I have just tried with mpif90, and it works:
![image](https://user-images.githubusercontent.com/32838731/87619707-68a1cf00-c74f-11ea-9864-a3ef51b935d1.png)

**Comment by jcklasseter** [comment]
Okay, thanks. Do you have any information on how it was installed? I had the same issue outside of Docker in my standalone Ubuntu Linux. I'm not sure if it's the gfortran (mpif90 --version shows ```GNU Fortran (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.```

When I run the same command as you:
```
Step 11/12 : RUN cd src && mpif90 -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o ~/SISSO.x
 ---> Running in 31eafd3e37e1
DI.f90:1033:74:

 1033 |      call mpi_send(totalm,1,mpi_integer8,0,1,mpi_comm_world,status,mpierr)
      |                                                                          1
Error: There is no specific subroutine for the generic 'mpi_send' at (1)
```

If I swap the use mpi like the readme says it's back to:
```
Step 12/13 : RUN cd src && mpif90 -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o ~/SISSO.x
 ---> Running in 528cb54d22d8
var_global.f90:18:13:

   18 | implicit none
      |             1
Error: IMPLICIT NONE statement at (1) cannot follow INTERFACE statement at (2)
```

**Comment by rouyang2017** [comment]
I see the difference. My mpif90 is based on ifort. Unfortunately I currently don't have a gfortran based mpif90 or mpigfortran available to test. But it was working as I did it with mpigfortran.

**Comment by jcklasseter** [comment]
Okay. So it seems like we are stuck on intel compilers then, which makes the code incredibly cumbersome to get running on a non-intel cluster like Summit... Is there no chance you'd be willing to look into the issue any further? Something like VirtualBox is free and cross platform to setup a testing environment, myself and others have been unable to build the program with gfortran based implementations. 

Any tips, tricks, or suggestions would also be appreciated... Even if it's just the version of mpigfortran.

**Comment by rouyang2017** [comment]
Ah, just an idea. v2.3 (in the folder Previous_Versions) was tested OK by me using gfortran based (see the Changlog). Could you have a try with that so we can know whether the problem comes from the code version or from you machine?

**Comment by jcklasseter** [comment]
That pointed me on the right track! I got all the issues fixed, and people can now run SISSO pretty much anywhere off of docker with https://github.com/jcklasseter/SISSO_docker

Some combination of switching back to the mpifort command, and building MPICH from source
