### ISSUE TITLE
Feature Scaling

### ISSUE THREAD

**Issue by vonruti** [rouyang2017/SISSO#3]
Could you add in the documentation if preprocessing such as feature scaling is necessary. As far as I understand you should not scale the features as otherwise the + and - operator for the physical feature construction does not make sense anymore. This is something I think is missing in the SISSO paper and would be useful to have in a documentation.

**Comment by rouyang2017** [comment]
Sorry for this confusion! Yes, you are right. SISSO does not do any feature scaling or normalisation to your input primary features for feature construction!  It is only after feature construction, then features are standardized for the SIS step for the feature selection purpose only!.  We will mention this in a coming SISSO-related paper! Thank you.
