### ISSUE TITLE
How to enter sample-weights in SISSO fits?

### ISSUE THREAD

**Issue by PGaneshIyer** [rouyang2017/SISSO#32]
Is there an example demonstrating how to enter sample-weights in SISSO ? 

Thanks.

**Comment by rouyang2017** [comment]
Sorry, the current SISSO code does not support sample-weighting.
However, it may not involve too much coding if needed.

**Comment by PGaneshIyer** [comment]
Thanks, yes for the problems I am working on, incorporating sample-weighting would be quite beneficial.  We can talk more offline on this topic.
