### ISSUE TITLE
correlation between features

### ISSUE THREAD

**Issue by mahditarighi** [rouyang2017/SISSO#34]
Dear Dr. Ouyang
Hi,
How I can calculate the correlation between different primary features which were implemented in the SISSO run?
Is there any built-in subroutine for doing this?

Best Regards.

**Comment by rouyang2017** [comment]
Hi, there is no calculation of correlation between primary features in the current SISSO code. However, we do have an ongoing project in my group to develop methods for variables selection and feature decorrelation with SISSO.

**Comment by mahditarighi** [comment]
It would be appreciated. 
Thank you.
