### ISSUE TITLE
Define matrix as input features

### ISSUE THREAD

**Issue by mahditarighi** [rouyang2017/SISSO#36]
Dear Dr. Ouyang
Is there any possibility to define a matrix as input features in SISSO code? such as coulomb matrix, which extensively used
in ML calculations.

Regards

**Comment by rouyang2017** [comment]
Hi, current implementation does not support the input of a matrix for single sample, but scalar features.  As the SISSO outcome is an explicit equation, we need ideas on how a matrix (and vector) can appear in the model as variables.

**Comment by mahditarighi** [comment]
thank you so much.
