### ISSUE TITLE
Classification input error

### ISSUE THREAD

**Issue by AlexGzyl** [rouyang2017/SISSO#37]
Hello, the error I'm getting is from sisso.f90 line 533 "no y value in the train.dat file for classification".
I was wondering how the code recognizes the columns? My input file is set up like the example input you have with the materials column followed by feature columns. I have specified the classes (#,#) accordingly.

[SISSO.txt](https://github.com/rouyang2017/SISSO/files/5876737/SISSO.txt)
[train.txt](https://github.com/rouyang2017/SISSO/files/5876742/train.txt)

**Comment by rouyang2017** [comment]
In train.dat, columns are separated by space. Except the first, all the columns are treated as features in the code.
The information of your classification samples are specified in SISSO.in. E.g. your nsample=(47,49) means the first 47 rows are of group1, and the following 49 rows of group2 in the train.dat

**Comment by AlexGzyl** [comment]
Thank you!
