### ISSUE TITLE
Running SISSO on Windows

### ISSUE THREAD

**Issue by testlablive** [rouyang2017/SISSO#38]
The current version v3.0.2 of SISSO has multiple system calls that are not available on Windows. Therefore SISSO won't run on Windows machines. It might be possible to use built-in Fortran functions rather than using system calls in future releases.

In the meantime if you want to run SISSO on a Windows machine, you can use the version [SISSO-for-windows](https://github.com/testlablive/SISSO-for-windows), which is an adapted version v3.0.2 of SISSO. All linux specific system calls are replaced with windows system calls.

**Comment by zarcoder** [comment]
thanks for your work
why this happend?
<img width="734" alt="Snipaste_2021-04-13_22-16-47" src="https://user-images.githubusercontent.com/2095041/114567603-fb9f7380-9ca5-11eb-9eca-3c839e1d3a68.png">

**Comment by testlablive** [comment]
It looks like the stack size of the compiler is set too low. If you are using Visual Studio you can set this via -F or -STACK and the stack size in bytes. For example:
mpiifort **-F 1000000000** -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o sisso.exe

**Comment by zarcoder** [comment]
> It looks like the stack size of the compiler is set too low. If you are using Visual Studio you can set this via -F or -STACK and the stack size in bytes. For example:
> mpiifort **-F 1000000000** -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o sisso.exe

thanks a lot
it works now

**Comment by rouyang2017** [comment]
Thanks Jonathan ! Will take care of that in future release.
