### ISSUE TITLE
SISSO-编译方法

### ISSUE THREAD

**Issue by zarcoder** [rouyang2017/SISSO#39]
# SISSO-编译方法

E-Mail: centos@vip.qq.com

SISSO安装使用mpiifort，需要安装intel编译工具，根据自身集群环境可进行选择版本以及调优，以下为测试过的版本

## Windows版本
thanks to @testlablive

### 软件版本

编译器：Intel.Parallel.Studio.XE.2019.Cluster.Edition

操作系统：Windows 10

SISSO-Windows：https://github.com/testlablive/SISSO-for-windows

### 编译安装

在Windows下编译时，使用下列的编译命令，在命令行中进行编译

- 下载源代码3.0.2版本
- 安装Intel.Parallel.Studio(安装完之后重启)

mpiifort  -F 100000000 -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o SISSO

### 软件版本

编译器：parallel_studio_xe_2019_update5_cluster_edition

操作系统：CentOS 7.6  (Ubuntu 18.04)

SISSO-Linux: https://github.com/rouyang2017/SISSO

### 编译安装

在Linux下编译安装时，注意安装前的检测，会提示安装g++，关于提示libc-32位版本的问题可以忽略

- 下载源码3.0.2版本
- 安装intel_parallel_studio之后，需要载入环境变量 
  - source $INTEL_INSTALL_DIR/parallel_studio_xe_2019/psxevars.sh
  - source $INTEL_INSTALL_DIR/intel/impi/2019.5.281/intel64/bin
  - 个人环境可放入.bashrc
- 运行时需要修改系统默认栈大小 ulimit -s unlimited

**Comment by zw1900686** [comment]
Sorry to bother you, but I have a silly question. How do I run the mpifort line of code after I install the specified compiler on the window system?

**Comment by testlablive** [comment]
Run the command in PowerShell

**Comment by zmk-1997** [comment]
> # SISSO-编译方法
> 电子邮件： [centos@vip.qq.com](mailto:centos@vip.qq.com)
> 
> SISSO安装使用mpiifort，需要安装intel编译工具，根据自身集群环境可进行选择版本以及调优，以下为测试过的版本
> 
> ## 视窗版本
> 感谢@testlablive
> 
> ### 软件版本
> 编译器：Intel.Parallel.Studio.XE.2019.Cluster.Edition
> 
> 操作系统：视窗 10
> 
> SISSO-Windows：https://github.com/testlablive/SISSO-for-windows
> 
> ### 编译安装
> 在Windows下编译时，使用下列的编译命令，在命令行中进行编译
> 
> * 下载源代码3.0.2版本
> * 安装Intel.Parallel.Studio（安装完之后重启）
> 
> mpiifort -F 100000000 -O2 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o SISSO
> 
> ## Linux版本安装
> ### 软件版本
> 编译器：parallel_studio_xe_2019_update5_cluster_edition
> 
> 操作系统：CentOS 7.6 （Ubuntu 18.04）
> 
> SISSO-Linux： https://github.com/rouyang2017/SISSO
> 
> ### 编译安装
> 在Linux下编译安装时，注意安装前的检测，会提示安装g++，关于提示libc-32位版本的问题可以忽略
> 
> * 下载源码3.0.2版本
> * 安装intel_parallel_studio之后，需要载入环境变量
>   * source $INTEL_INSTALL_DIR/parallel_studio_xe_2019/psxevars.sh
>   * 来源 $INTEL_INSTALL_DIR/intel/impi/2019.5.281/intel64/bin
>   * 个人环境可放入.bashrc
> * 运行时需要修改系统默认栈大小 ulimit -s unlimited

请问在windows下要怎么编译出SISSO程序呢？显示mpiifort命令找不到

>

**Comment by luhongan226** [comment]
I obtained the following content after compiling on Windows
![Uploading 捕获.JPG…]()
mpifc.bat for the Intel(R) MPI Library 2021.11 for Windows*
Copyright Intel Corporation.

You have to source <Intel MPI>\bin\mpivars.bat
I have installed MPI

**Comment by Xing2Wen** [comment]
Sorry to bother you, when I double-click SISSO.exe on Windows, it crashes immediately, and nothing happens. Even when I run the executable from the command line, I still don’t get any output. Is this normal?
