### ISSUE TITLE
Documentation or tutorials?

### ISSUE THREAD

**Issue by hgandhi2411** [rouyang2017/SISSO#40]
Dr. Ouyang,

Is it possible to create documentation or maybe a tutorial explaining different parameters that can be used to run this SISSO code for different tasks? I'm a new FORTRAN user and have been trying to reproduce your regression example. I was finally able to make it work with difficulty. It might be nice to have an end-to-end tutorial for new users like me and will encourage a larger community to use this excellent code.

**Comment by rouyang2017** [comment]
Thanks hgandhi2411. Yes, I also feel it is increasingly necessary to create a user's guide. Will do it this year.

**Comment by hgandhi2411** [comment]
In the mean time, can you please help me understand what's wrong with this input script? I'm attaching SISSO.in and train.dat.

![image](https://user-images.githubusercontent.com/22055417/117665898-5034f200-b171-11eb-8ae4-4715f2b95252.png)
![image](https://user-images.githubusercontent.com/22055417/117665923-56c36980-b171-11eb-99c7-1fa35ba0a8ea.png)

**Comment by rouyang2017** [comment]
OK, let me give a try

**Comment by hgandhi2411** [comment]
Here is the text version of my files:
SISSO.in
``` FORTRAN
!_________________________________________________________________
! keywords for the target properties                               
!_________________________________________________________________
ptype=1                               
ntask=1                               
nsample=25                            ! number of samples for each task
task_weighting=1
desc_dim=4                            ! dimension of the descriptor  
restart=.false.                       ! set .true. to continue a job that was stopped but not yet finished 
!_________________________________________________________________
!keywords for feature construction and sure independence screening 
!_________________________________________________________________
nsf=3                                 ! number of scalar features (one feature is one number for each material)
rung=2                                ! rung (<=3) of the feature space to be constructed (times of applying the opset recursively)
opset='(+)(-)(*)(/)(exp)(^-1)(sin)(cos)'      ! (sinh)(tanh)'
maxcomplexity=10                      ! max feature complexity (number of operators in a feature)
dimclass=(1:3)                    ! group features according to their dimension/unit; those not in any () are dimensionless
maxfval_lb=1e-3                       ! features having the max. abs. data value < maxfval_lb will not be selected 
maxfval_ub=1e5                        ! features having the max. abs. data value > maxfval_ub will not be selected
subs_sis=100                          ! size of the SIS-selected (single) subspace for each descriptor dimension
!_________________________________________________________________
!keywords for descriptor identification via a sparsifying operator
!_________________________________________________________________
method='L0'                           ! sparsification operator: 'L1L0' or 'L0'; L0 is recommended!
fit_intercept=.false.                 ! fit to a nonzero intercept (.true.) or force the intercept to zero (.false.)
metric='RMSE'                         ! for regression only, the metric for model selection: RMSE,MaxAE
nm_output=50                          ! number of the best models to output
```

train.dat
```
materials	del_P_by_L	pipe_D	elbow_angle	inlet_v
sample1	0.77962398	0.021	1.0	0.011
sample2	0.12539223	0.055	9.0	0.011
sample3	0.31596343	0.049	13.0	0.02
sample4	1.548262	0.022	20.0	0.02
sample5	0.22665419	0.084	47.0	0.02
sample6	2.1042648	0.01	48.0	0.006
sample7	0.049643078	0.079	49.0	0.006
sample8	1.0513706	0.013	50.0	0.005
sample9	1.5713076	0.032	53.0	0.025
sample10	0.20413389	0.053	57.0	0.01
sample11	0.092338423	0.1	71.0	0.011
sample12	0.62038283	0.054	83.0	0.021
sample13	1.2336624	0.014	84.0	0.006
sample14	0.054440061	0.083	84.0	0.006
sample15	0.091553684	0.069	92.0	0.007
sample16	3.1905766	0.014	93.0	0.013
sample17	0.065200976	0.075	99.0	0.006
sample18	0.56094855	0.067	106.0	0.025
sample19	0.56709911	0.038	111.0	0.013
sample20	0.36515745	0.075	112.0	0.021
sample21	1.5852126	0.027	129.0	0.018
sample22	0.9067224	0.021	131.0	0.008
sample23	0.50116911	0.067	153.0	0.022
sample24	0.13620762	0.064	159.0	0.008
sample25	0.11003728	0.097	180.0	0.011
```

**Comment by rouyang2017** [comment]
I see the problem. In the file train.dat, you have may Tab symbols which can not be identified in the SISSO code. It works when I replace all the Tab with space symbols.

**Comment by rouyang2017** [comment]
That seems a code bug. Are you using an early version of the code?

If I am using the version 3.0.2, then I got normal results:
  4D descriptor (model): 
Total RMSE,MaxAE:   0.043247  0.117872
@@@descriptor: 
                      2:[((inlet_v/pipe_D)/pipe_D)]
                     15:[(exp(inlet_v)*(inlet_v/pipe_D))]
                    228:[(exp(inlet_v)/(pipe_D*elbow_angle))]
                    295:[((pipe_D/elbow_angle)/(inlet_v*elbow_angle))]
       coefficients_001:     0.3839017519E-01    0.1011939347E+01   -0.3901951487E+00    0.9466491704E+01
          Intercept_001:     0.0000000000E+00
         RMSE,MaxAE_001:     0.4324744046E-01    0.1178723436E+00
================================================================================

**Comment by rouyang2017** [comment]
That seems a code bug. Are you using an early version of the code?

 If I am using the version 3.0.2, then I got normal results:
  4D descriptor (model): 
Total RMSE,MaxAE:   0.043247  0.117872
@@@descriptor: 
                      2:[((inlet_v/pipe_D)/pipe_D)]
                     15:[(exp(inlet_v)*(inlet_v/pipe_D))]
                    228:[(exp(inlet_v)/(pipe_D*elbow_angle))]
                    295:[((pipe_D/elbow_angle)/(inlet_v*elbow_angle))]
       coefficients_001:     0.3839017519E-01    0.1011939347E+01   -0.3901951487E+00    0.9466491704E+01
          Intercept_001:     0.0000000000E+00
         RMSE,MaxAE_001:     0.4324744046E-01    0.1178723436E+00
