### ISSUE TITLE
About the number of operators

### ISSUE THREAD

**Issue by jumpwan** [rouyang2017/SISSO#44]
Hello,Dr Ouyang!
When I set rung=3, I find in my Uspace.name file all formulas have 7 operators, less than the maxcomplexity=10 that I set, which seems to not work. So if I want more complicated formula, should I set rung=4 or more? Does the maxcomplexity parameter only work when rung=3 and maxcomplexity <7 ?
Or if I was wrong, please tell me the maximum operaters rung=3 can reach.
Thank you very much!

**Comment by rouyang2017** [comment]
You are right, with rung=3, the actual feature complexity only has maximum of 7, though you set the maximal limit to be 10. If you want features with higher complexity, please increase rung, which then require massive amount of memory and may prevent you doing so. You can give a try and see.
