### ISSUE TITLE
Installation Help (no prior experience with fortran)

### ISSUE THREAD

**Issue by calvs01** [rouyang2017/SISSO#45]
Hello, 

Sorry to bother you, but I'm not familiar with fortran compilers at all. 
I read your advice on some other issue comments so I installed Intel Fortran Compiler and the Intel MPI Library based on your links for windows. I also installed powershell. 
In powershell, I set the directory to the location of src and pasted your recommended installation code. 

This just returned "You have to source <Intel MPI>\bin\mpivars.bat"

Given that I don't know anything about the procedure I'm trying to implement, is there any relevant tutorial you might recommend to help me understand how to properly compile the fortran files to windows executables?

Thank you

**Comment by rouyang2017** [comment]
Hi, usually we install the code in Linux systems, and run the SISSO code in parallel on computer clusters. Unfortunately I have no experience and don't know how to compile a Fortran code to windows executables.
