### ISSUE TITLE
Compiling this code with NVDIA support compiler

### ISSUE THREAD

**Issue by siyu-g** [rouyang2017/SISSO#47]
Hi Runhai,

I am trying to compile this code on ALCF Polaris machine. The problem is that they don't have mpiifort compiler. The compiler I used on that machine was nvhpc. But that leads to some error while building SISSO.f90. Some of the functions are build-in functions of ifport and intel. I tried to compile ifport by hand. But after compiling ifport there is still some error:
################################
ftn -Mfree -acc -mp=multicore,gpu -gpu=cc80  -Mcudalib=cublas,cufft -Mcuda=lineinfo -traceback -Minfo=mp,acc -gopt -traceback -cpp ifport.f90 var_global.f90 libsisso.f90 DI.f90 FC.f90 SISSO.f90 -o ../bin/SISSO
ifport.f90:
NVFORTRAN-W-0119-Redundant specification for sizeof_time_t (ifport.f90: 51)
NVFORTRAN-W-0119-Redundant specification for sizeof_size_t (ifport.f90: 52)
NVFORTRAN-W-0119-Redundant specification for sizeof_clock_t (ifport.f90: 53)
  0 inform,   3 warnings,   0 severes, 0 fatal for ifport_types
var_global.f90:
libsisso.f90:
DI.f90:
FC.f90:
SISSO.f90:
/usr/bin/ld: DI.o: in function `di_model_':
/home/siyugao/Polaris/SISSO/SISSO-master/src/DI.f90:542: undefined reference to `isnan_'
/usr/bin/ld: /home/siyugao/Polaris/SISSO/SISSO-master/src/DI.f90:523: undefined reference to `isnan_'
/usr/bin/ld: /home/siyugao/Polaris/SISSO/SISSO-master/src/DI.f90:507: undefined reference to `isnan_'
/usr/bin/ld: SISSO.o: in function `MAIN_':
/home/siyugao/Polaris/SISSO/SISSO-master/src/SISSO.f90:94: undefined reference to `makedirqq_'
/usr/bin/ld: /home/siyugao/Polaris/SISSO/SISSO-master/src/SISSO.f90:95: undefined reference to `makedirqq_'
/usr/bin/ld: /home/siyugao/Polaris/SISSO/SISSO-master/src/SISSO.f90:96: undefined reference to `makedirqq_'
pgacclnk: child process exit status 1: /usr/bin/ld
################################
Since I don't want to make any change to your code, in case I might screw it, do you have other suggestions to build the code with GPU support? Is there anyone else trying to build the code on GPUs?

**Comment by rouyang2017** [comment]
Hi Siyu, unfortunately I am not able to help with this because of no experience using GPU.
