### ISSUE TITLE
SISSO error

### ISSUE THREAD

**Issue by xiangqian122** [rouyang2017/SISSO#48]
Hi Dr Ouyang!
     I am sorry to bother you, but I am a new learner in SISSO. The problem is that I want to do regression by SISSO, but I don't kown hao to deal with this problem, I am not sure it is input file errror whether or compile error, but it run successfully at the beginner. Here is the error picture，thank you very much and look forward to your suggestions.
                                                                 
![image](https://user-images.githubusercontent.com/75673712/190832071-c401a926-b5cb-42ed-8647-ba2df718c315.png)

**Comment by panayu123** [comment]
请问这个问题解决了吗？我也是初学者，也遇到了同样的问题
