### ISSUE TITLE
Folder residul related issues

### ISSUE THREAD

**Issue by join-xu2021** [rouyang2017/SISSO#50]
Hello
I hope this email finds you well. I have a question regarding the "residual" folder that is generated by the model. I would appreciate it if you could provide me with more details about its purpose and contents, as I'm not quite clear on its specifics.

Could you kindly explain what the "residual" folder represents? I'm particularly interested in understanding its functionality and the role it plays in the generated output. Additionally, if you could provide any information regarding the files typically found within the "residual" folder, it would greatly assist me in gaining a better understanding of its significance.

Thank you very much for your time and assistance. I look forward to your prompt response.

**Comment by rouyang2017** [comment]
Hi,
The 'residual' folder contains the residual information of each dimension, i.e. the delta_nD as shown in the Figure 1 in the SISSO paper. It is usually not useful, and no longer present in the recent versions.
