### ISSUE TITLE
Error while reading file "train.dat"

### ISSUE THREAD

**Issue by danielpert** [rouyang2017/SISSO#51]
I am trying to run SISSO but the only output I got is this error message:
```
Error while reading file "train.dat" !!!
```

The contents of SISSO.out are as follows:
```
****************************************************************
  Sure Independence Screening and Sparsifying Operator (SISSO)
             Version SISSO.3.2, September, 2022.
****************************************************************

Read in data from train.dat.
```

It does not specify what the error while reading 'train.dat' actually is so I am pretty lost. I double checked and my train.dat has the correct number of rows and columns based on SISSO.in, and the names of the rows have no spaces or mathematical operators.

**Comment by rouyang2017** [comment]
Hi, I can give a try if could send me the train.dat.

**Comment by danielpert** [comment]
Yes I have emailed it to you

**Comment by rouyang2017** [comment]
I see the problem. The comma, space, and Tab in train.dat are treated as separators in the code, and you have commas in the strings of your molecule names which is not allowed. It works if I remove the comma in the molecule name strings.

**Comment by danielpert** [comment]
oh wow thanks! For the future it would be helpful if it gave a more specific error message when something like this happens so users can easily figure out what the problem is

**Comment by rouyang2017** [comment]
Yes, thanks. Will  do this.
