### ISSUE TITLE
The f90 file failed to compile during installation.

### ISSUE THREAD

**Issue by Senppoa** [rouyang2017/SISSO#55]
Hi, Dr. Ouyang
Sorry to bother you,  I have installed all dependencies of SISSO, but when encountering such an error during compilation, how should I solve it?  Also I have tried the methods in readme to solve this error, but it is still not work.

![f7a924642f6042f4140d53a2277a9a3](https://github.com/rouyang2017/SISSO/assets/44549341/2fd854cf-d4bd-4bbf-8acd-88a694eb66a7)

**Comment by rouyang2017** [comment]
Is it because that you do not have write permission in your folder? The programs are OK here.

**Comment by Senppoa** [comment]
Thank you! I have fixed this problem, it is indeed caused by the write permission issues of the `~/bin` folder.
