### ISSUE TITLE
Issue with SISSO_predict 

### ISSUE THREAD

**Issue by dsdavide** [rouyang2017/SISSO#56]
Hi, I am trying out SISSO with a very basic use case (train.data) from the template folder. 

SISSO seems to run fine, but when I try to make prediction I get the following error:

>  dimension:            1
 feature: (feature1+(feature2+feature3))
 intercept:   -1.02880826200000
 coefficients:    1.86133553200000
sh: 1: bc: not found
sh: 1: bc: not found
sh: 1: bc: not found
sh: 1: bc: not found
sh: 1: bc: not found
forrtl: severe (24): end-of-file during read, unit 111, file /home/ddistefa/SISSO-master/sisso_test2/desc_tmp
Image              PC                Routine            Line        Source
SISSO_predict      000000000042B636  Unknown               Unknown  Unknown
SISSO_predict      0000000000407E80  Unknown               Unknown  Unknown
SISSO_predict      0000000000405B14  Unknown               Unknown  Unknown
SISSO_predict      000000000040419D  Unknown               Unknown  Unknown
libc.so.6          00007F320A531D90  Unknown               Unknown  Unknown
libc.so.6          00007F320A531E40  __libc_start_main     Unknown  Unknown
SISSO_predict      00000000004040B5  Unknown               Unknown  Unknown

**Comment by siyu-g** [comment]
Hi, I got similar issue when training the model. How did you solve that?

forrtl: severe (24): end-of-file during read, unit -5, file Internal List-Directed Read
Image              PC                Routine            Line        Source
SISSO              000000000049ED08  Unknown               Unknown  Unknown
SISSO              00000000004C4AF2  Unknown               Unknown  Unknown
SISSO              00000000004961D3  Unknown               Unknown  Unknown

**Comment by dsdavide** [comment]
Hi, not sure is related to my issue. In my case there was an issue with the installation of bc, I reinstalled it an it worked.
