### ISSUE TITLE
VarSelect_SISSO.py KeyError 

### ISSUE THREAD

**Issue by ZengnianMa** [rouyang2017/SISSO#69]
Thanks to author. When I run the VarSelect_SISSO.py, there was an error about dimension. I tried to change the dimension number, but it was also failed.
![Snipaste_2024-08-25_20-03-29](https://github.com/user-attachments/assets/3b1fae21-354d-4d80-a08b-3a32cbcdc1ee)
Traceback (most recent call last):
  File "/home/mzn/N2/Adsorption/test/VarSelect_SISSO.py", line 502, in <module>
    selected_features, RMSE = SISSO_out_reader('./%s' % str(i), desc_dim, all_features, initial_maths_operators)
  File "/home/mzn/N2/Adsorption/test/VarSelect_SISSO.py", line 67, in SISSO_out_reader
    return feature_list, total_RMSE_dict[dimension]
KeyError: 1

Traceback (most recent call last):
  File "/home/mzn/N2/Adsorption/test/VarSelect_SISSO.py", line 502, in <module>
    selected_features, RMSE = SISSO_out_reader('./%s' % str(i), desc_dim, all_features, initial_maths_operators)
  File "/home/mzn/N2/Adsorption/test/VarSelect_SISSO.py", line 67, in SISSO_out_reader
    return feature_list, total_RMSE_dict[dimension]
KeyError: 2

**Comment by rouyang2017** [comment]
Hi, that error may be caused by the format change in the SISSO.out in the new version 3.5, and I haven't got chance to  correspondingly update the tools in the 'utilities'.

**Comment by ZengnianMa** [comment]
> Hi, that error may be caused by the format change in the SISSO.out in the new version 3.5, and I haven't got chance to correspondingly update the tools in the 'utilities'.

Thanks for your response. Look forward to your update.

**Comment by rouyang2017** [comment]
VarSelect_SISSO.py has been updated. Now it should work.

**Comment by ZengnianMa** [comment]
> VarSelect_SISSO.py has been updated. Now it should work.

It can work. Thanks a million.
