### ISSUE TITLE
multi task learning - input

### ISSUE THREAD

**Issue by vonruti** [rouyang2017/SISSO#8]
Could you provide an example of a train.dat file for multi-task learning?

**Comment by rouyang2017** [comment]
Hi! The 'train.dat_quali_multitask' and 'train.dat_quanti_multitask' in the input_template folder have the format for users to easily preparing their train.dat files for multi-task learning.  Please check if that is OK for your need.

**Comment by vonruti** [comment]
Hi, yes thanks. I did not see that you uploaded a new version.
